# Problem 1

In [124]:
import numpy as np

In [125]:
a = np.array([1,2,3,4])   # 1D Array
print(a)

[1 2 3 4]


In [126]:
a = np.array([[1,2,3],[3,4,5]])  #2D Array
print(a)

[[1 2 3]
 [3 4 5]]


# Problem 2

In [127]:
a = np.array([3,6,5])
b = np.array([1,2,5])

In [ ]:
# addition 
print(a+b)
# subtraction
print(a-b)
# multiplication element to element (matrix multiplication at end)
print(a*b) 
# division
print(a/b)
# eponent
print(a**2)

[ 4  8 10]
[2 4 0]
[ 3 12 25]
[3. 3. 1.]
[ 9 36 25]


# Problem 3

In [129]:
a = np.array([3,6,5])
# maximum 
print(np.max(a))
# minimum
print(np.min(a))
# mean 
print(np.mean(a))
# sum
print(np.sum(a))

6
3
4.666666666666667
14


# Problem 4 

In [130]:
# Reshaping
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)

a = a.reshape((4,2))
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


# Problem 5

In [131]:
# slice and get only last two rows
print(a[2:])

# slice and get only second column
print(a[:, 1:])

# slice and index lets say we want print only 6
print(a[2, 1:])

# now we want print only 6 and 7
print(a[2, 1:], a[3, :1])

[[5 6]
 [7 8]]
[[2]
 [4]
 [6]
 [8]]
[6]
[6] [7]


In [136]:
# using indexing to change an element 
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

# change 8 to 16
a[-1, 3:] *= 2
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 5  6  7 16]]


In [133]:
# true matix multiplication (order of the matrix matters)
a = np.ones((2,3))
print(a.shape) 
print(a)
b = np.full((3,2), 2)
print(b.shape)
print(b)
print(np.matmul(a,b))

(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]
(3, 2)
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
